### ISSUE TITLE
QS vol change triggers pip mode

### ISSUE THREAD

**Issue by RahifM** [SimonMarquis/Android-SoundQuickSettings#1]
After the latest update version 1.0.2 on oct 11 the quick settings volume change triggers the picture in picture mode, i have reverted back to version 1.0.0 and fixed the issue for now hope the next update will fix this issue

thanks and good day sir

**Comment by SimonMarquis** [comment]
Hi @RahifM, thanks for the report.
This is something I didn't anticipate.
The reason is because https://github.com/SimonMarquis/Android-SoundQuickSettings/commit/60e3f16e76b2f73afe981def165d8f4e26fb2c0c#diff-151b12d761652fd733c4786373da3d875d9c7b03ca858de3f539734b0ec9bd70L13-L14

where I replaced the deprecated (and now crashing) `sendBroadcast(Intent(ACTION_CLOSE_SYSTEM_DIALOGS))` with `startActivityAndCollapse`. Unfortunately this starts a NoDisplay Activity but still triggers the picture-in-picture mode.

One workaround is to use the alternative `showDialog`, it seems to work fine on my end.
All this is to automatically collapse the notification shade after the QS click.
Is this a behavior that you rely on? I'm trying to figure out how people are using this QS Tile :)

**Comment by RahifM** [comment]
im sorry sir i dont understand how the code works? 😅

but yes the behaviour of closing notification shade on qs click without the pip mode trigger is preferred, that is how it is currently on the old version 1.0.0

**Comment by SimonMarquis** [comment]
Ok, then I'll push a fix right now.

**Comment by SimonMarquis** [comment]
[Version 1.0.3](https://github.com/SimonMarquis/Android-SoundQuickSettings/releases/tag/1.0.3) has been pushed to the play store, and should be available in a few minutes. You can also manually update it by downlading the release APK directly from the release page.

**Comment by RahifM** [comment]
Thanks for the quick update sir, it is now fixed and working as expected :)
