### ISSUE TITLE
Tile showing as unavailable after device reboot

### ISSUE THREAD

**Issue by argh0815** [SimonMarquis/Android-SoundQuickSettings#4]
Hi there, sorry to bother you again. After your last fix, forcing Active Mode for the tile, I noticed after a while that the tile shows as unavailable after newly adding it to the quick settings or after a device reboot. However, after tapping on it once, it enables itself and shows the volume slider. This happens on Google Pixel 4a, Android 13 as well as Lenovo Yoga Tab 13, Android 12. 

I then added
```
    override fun onTileAdded() {
        super.onTileAdded()
        qsTile.state = Tile.STATE_INACTIVE
        qsTile.updateTile()
    }
```
to SoundTileService.kt and that resolved it. Since I'm not familiar with Android programming, just wanted to check with you whether this is a proper way of somewhat initializing the tile.

**Comment by SimonMarquis** [comment]
Hi. Unfortunately, I think forcing ACTIVE_MODE in https://github.com/SimonMarquis/Android-SoundQuickSettings/issues/3 was not really a good thing.

> Source: https://developer.android.com/develop/ui/views/quicksettings-tiles#tile-states
> - [STATE_ACTIVE](https://developer.android.com/reference/android/service/quicksettings/Tile.html?utm_campaign=adp_series_quicksettingstiles_092916&utm_source=medium&utm_medium=blog#STATE_ACTIVE): Indicates an on or enabled state. The user can interact with your tile while in this state.
For example, for a fitness app tile that lets users initiate a timed workout session, STATE_ACTIVE would mean that the user has initiated a workout session and the timer is running.
> - [STATE_INACTIVE](https://developer.android.com/reference/android/service/quicksettings/Tile.html?utm_campaign=adp_series_quicksettingstiles_092916&utm_source=medium&utm_medium=blog#STATE_INACTIVE): Indicates an off or paused state. The user can interact with your tile while in this state.
To use the fitness app tile example again, a tile in STATE_INACTIVE would mean that the user hasn't initiated a workout session, but could do so if they wanted to.
> - [STATE_UNAVAILABLE](https://developer.android.com/reference/android/service/quicksettings/Tile.html?utm_campaign=adp_series_quicksettingstiles_092916&utm_source=medium&utm_medium=blog#STATE_UNAVAILABLE): Indicates a temporarily unavailable state. The user cannot interact with your tile while in this state.
> ![](https://developer.android.com/static/develop/ui/views/images/state-hues.png)

The "dimmed icon" might be something else.
I'll try to revert the changes and force updating the tile state like you proposed.

**Comment by SimonMarquis** [comment]
> [onTileAdded()](https://developer.android.com/reference/android/service/quicksettings/TileService#onTileAdded()): This method is called only when the user adds your tile for the first time, and if the user removes and adds your tile again.

Also, when adding the meta-data in the previous commit

```xml
            <meta-data
                android:name="android.service.quicksettings.ACTIVE_TILE"
                android:value="true" />
```

The tile always becomes "unavailable" after a restart...

**Comment by argh0815** [comment]
I agree, this icon dimming/tile availability thingy seems to be a bit of a lottery and depend on the Android flavour. I saw that description of onTileAdded before and was quite surprised that the inactive status survived a reboot on my devices. Another option might be to use onStartListening() or onCreate() instead.

One other approach that worked for me with force active mode was to use this instead of setting the inactive status:

```
override fun onCreate() {
        super.onCreate()
        requestListeningState(this, ComponentName(this, javaClass))
}
```

**Comment by SimonMarquis** [comment]
[requestListeningState()](https://developer.android.com/reference/android/service/quicksettings/TileService#requestListeningState(android.content.Context,%20android.content.ComponentName)): Requests that a tile be put in the listening state so it can send an update. This method is only applicable to tiles that have [META_DATA_ACTIVE_TILE](https://developer.android.com/reference/android/service/quicksettings/TileService#META_DATA_ACTIVE_TILE) defined as true on their TileService Manifest declaration, and will do nothing otherwise.

[META_DATA_ACTIVE_TILE](https://developer.android.com/reference/android/service/quicksettings/TileService#META_DATA_ACTIVE_TILE): Active mode is for tiles which already listen and keep track of their state in their own process.

Given these two pieces of documentation, I don't think this applies to the situation you're experiencing. While it might seem it solves the issue, I don't think this is a real fix for the root cause.

Are you still reproducing the dimmed icon issue when there is no `ACTIVE_TILE` meta-data (and no Tile.updateTile() or requestListeningState())? Because I'm not able to reproduce this on my devices.

**Comment by argh0815** [comment]
Yes, on my Lenovo Yoga Tab 13 the icon is dimmed without ACTIVE_TILE, however, on my Pixel 4a, it's working correctly with your original version 1.0.3. Looks like an issue with the Lenovo Android flavour, so probably best for you to ignore this particular case - don't want to create problems for all the other users of the app.

**Comment by SimonMarquis** [comment]
Yeah, it might be an OEM specific issue.
I'll revert those changes and re-upload the app.
Sorry about that.
