### ISSUE TITLE
Not working on realme gt 6t

### ISSUE THREAD

**Issue by sumanbk92** [SimonMarquis/Android-SoundQuickSettings#9]
After installing this app, when I click on the widget, the volume control pop up is not coming and it's just does nothing.

See the video attached with this issue.

https://github.com/user-attachments/assets/cd33ee4d-5ade-47f1-bd95-c792efc0aebd

Both installing with apk from this repo's release page as well as from playstore not working.

Version: 1.0.6

**Comment by SimonMarquis** [comment]
Hi @sumanbk92 , can you tell me what happens if you long press the shortcut instead?

**Comment by sumanbk92** [comment]
Hi @SimonMarquis when I long press on the widget icon, I get the volume control popup.

I was surprised about this. No problem, I can close this issue if there's an enhancement planned for the pop up being opened on just tap instead of long press.

![Screenshot_2024-12-28-11-30-06-65_fc704e6b13c4fb26bf5e411f75da84f2](https://github.com/user-attachments/assets/c4a8070c-4fdd-40f4-8728-30f851c1a413)

**Comment by SimonMarquis** [comment]
No unfortunately I won't be able to do anything here. It is as if your OS does not provide any sound popup in lite version, but only the full sound settings sheet.

**Comment by Dani3I** [comment]
@SimonMarquis 
> No unfortunately I won't be able to do anything here. It is as if your OS does not provide any sound popup in lite version, but only the full sound settings sheet.

I have the same issue on my motorola phone. Long press opens "full options" but when I only click it, then it does nothing. It is a little problematic because in "full menu" I can't control volume of each app separately, as I can do when I click volume button. And also full screen menu stops media playback when it is opened

This is how not-full-menu version of volume control looks in my phone:
![Screenshot_20250114-131437 Fennec](https://github.com/user-attachments/assets/4a6e10d9-148f-4250-b630-e185d2a12390)
